#!/usr/bin/perl

use strict;
use warnings;

if ( !-e "/usr/local/cpanel/build-tools" ) {
    print "/usr/local/cpanel/build-tools is missing, running sandboxify...\n";
    system( "wget", "-O", "/root/sandboxify", "https://go.cpanel.net/sandboxify" );
    system( "sh", "/root/sandboxify" );
    if ( $? != 0 ) {
        die "sandboxify failed";
    }
}

print "Building the controller...\n";

system(qq{export PATH="/usr/local/cpanel/3rdparty/bin:/usr/local/cpanel/build-tools:/usr/local/sandbox-utils/bin:/usr/local/cpanel/t/qa/bin:\$PATH"; cd /usr/local/cpanel/t/qa ; make controller});

my $hostname = `hostname`;
chomp $hostname;

print "Now access the controller UI at:\n";
print "https://$hostname:1337/login.php\n";

